"use client";

import { motion } from "framer-motion";
import { Heart, Leaf, IndianRupee, Package } from "lucide-react";
import { AnimatedCounter } from "@/components/shared/animated-counter";

export interface ImpactMetrics {
  medicines_rescued: number;
  patients_helped: number;
  waste_prevented_kg: number;
  cost_saved_inr: number;
  cost_saved_display?: string;
}

export function ImpactBanner({ metrics }: { metrics: ImpactMetrics }) {
  const costDisplay =
    metrics.cost_saved_display ||
    (metrics.cost_saved_inr >= 100000
      ? `₹${(metrics.cost_saved_inr / 100000).toFixed(1)} Lakhs`
      : `₹${Math.round(metrics.cost_saved_inr / 1000)}K`);

  const items = [
    {
      icon: Package,
      label: "Medicines rescued",
      value: metrics.medicines_rescued,
      suffix: "",
    },
    {
      icon: Heart,
      label: "Patients supported",
      value: metrics.patients_helped,
      suffix: "",
    },
    {
      icon: IndianRupee,
      label: "Healthcare value redistributed",
      value: metrics.cost_saved_inr,
      display: costDisplay,
    },
    {
      icon: Leaf,
      label: "Medical waste prevented",
      value: metrics.waste_prevented_kg,
      suffix: " Kg",
    },
  ];

  return (
    <motion.section
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      className="glass-card rounded-2xl border border-blue-600/20 bg-gradient-to-br from-blue-600/10 to-green-600/10 p-6 sm:p-8 mb-8"
    >
      <p className="text-xs font-semibold uppercase tracking-widest text-blue-600 dark:text-blue-400 mb-1">
        Social impact
      </p>
      <h2 className="text-xl sm:text-2xl font-bold mb-6">
        Impact Generated By MediBridge
      </h2>
      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {items.map((item, i) => (
          <motion.div
            key={item.label}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.08 }}
            className="text-center sm:text-left"
          >
            <item.icon className="h-6 w-6 text-green-600 mx-auto sm:mx-0 mb-2" />
            <p className="text-2xl sm:text-3xl font-bold tabular-nums">
              {item.display ? (
                item.display
              ) : (
                <AnimatedCounter value={item.value} suffix={item.suffix} />
              )}
            </p>
            <p className="text-sm text-muted-foreground mt-1">{item.label}</p>
          </motion.div>
        ))}
      </div>
    </motion.section>
  );
}
